title: Pavan Chavan
logo: "/pavan.png"
description: >
  <br>
  Software Engineer | Frontend Developer
  <br>
  <a href="https://www.linkedin.com/in/thepavanchavan">
    <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:thepavanchavan@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
